spring:
  application:
    name: smer dnevnik
  datasource:
    url: jdbc:h2:mem:testdb
    username: su
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
#    defer-datasource-initialization: true - убрали настройку потому что отключили Hibernate и создаем и наполняем таблицы сами
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

server:
  port: 8080